filter:
    excluded_paths:
        - tests/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit  --configuration tests/phpunit.xml --coverage-clover=coverage.clover tests/'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'